<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */

use App\Client;
use Faker\Generator as Faker;

$factory->define(Client::class, function (Faker $faker) {
    return [
        'nrc_entrp' => $faker->uuid,
        'raisoci' => $faker->sentence($nbWords = 6, $variableNbWords = true),
        'formjury' => $faker->sentence($nbWords = 6, $variableNbWords = true),
        'dt_creat' => $faker->dateTime($max = 'now', $timezone = 'Europe/Paris'),
        'obj_soci' => $faker->sentence($nbWords = 6, $variableNbWords = true),
        'capt_soci' => $faker->sentence($nbWords = 6, $variableNbWords = true),
        'sect_activ' => $faker->sentence($nbWords = 6, $variableNbWords = true),
        'giac_rattach' => $faker->sentence($nbWords = 6, $variableNbWords = true),
        'ice' => $faker->randomNumber($nbDigits = NULL, $strict = false),
        'id_fiscal' => $faker->randomNumber($nbDigits = NULL, $strict = false),
        'id_entrp' => $faker->randomNumber($nbDigits = NULL, $strict = false),
        'ncnss' => $faker->randomNumber($nbDigits = NULL, $strict = false),
        'npatente' => $faker->randomNumber($nbDigits = NULL, $strict = false),
        'sg_soci' => $faker->address,
        'chif_aff_1' => $faker->randomFloat($nbMaxDecimals = NULL, $min = 0, $max = NULL),
        'chif_aff_2' => $faker->randomFloat($nbMaxDecimals = NULL, $min = 0, $max = NULL),
        'chif_aff_3' => $faker->randomFloat($nbMaxDecimals = NULL, $min = 0, $max = NULL),
        'chif_aff_4' => $faker->randomFloat($nbMaxDecimals = NULL, $min = 0, $max = NULL),
        'local_2' => $faker->address,
        'ville' => $faker->cityPrefix,
        'effectif' => $faker->numberBetween($min = 10, $max = 100),
        'mass_salar' => $faker->randomFloat($nbMaxDecimals = NULL, $min = 0, $max = NULL),
        'tax_form_pers' => $faker->randomFloat($nbMaxDecimals = NULL, $min = 0, $max = NULL),
        'der_annee_csf' => $faker->dateTime($max = 'now', $timezone = 'Europe/Paris'),
        'nb_permanent' => $faker->numberBetween($min = 10, $max = 100),
        'nb_occasional' => $faker->numberBetween($min = 10, $max = 100),
        'nb_ouvrier' => $faker->numberBetween($min = 10, $max = 100),
        'nb_cadre' => $faker->numberBetween($min = 10, $max = 100),
        'IF1_1' => $faker->sentence($nbWords = 6, $variableNbWords = true),
        'DS1_2' => $faker->sentence($nbWords = 6, $variableNbWords = true),
        'PF1_3' => $faker->sentence($nbWords = 6, $variableNbWords = true),
        'IF2_1' => $faker->sentence($nbWords = 6, $variableNbWords = true),
        'DS2_2' => $faker->sentence($nbWords = 6, $variableNbWords = true),
        'PF2_3' => $faker->sentence($nbWords = 6, $variableNbWords = true),
        'IF3_1' => $faker->sentence($nbWords = 6, $variableNbWords = true),
        'DS3_2' => $faker->sentence($nbWords = 6, $variableNbWords = true),
        'PF3_3' => $faker->sentence($nbWords = 6, $variableNbWords = true),
        'annee_deja1' => $faker->year($max = 'now'),
        'annee_deja2' => $faker->year($max = 'now'),
        'annee_deja3' => $faker->year($max = 'now'),
        'tel_1' => $faker->phoneNumber,
        'tel_2' => $faker->phoneNumber,
        'fix_1' => $faker->phoneNumber,
        'fix_2' => $faker->phoneNumber,
        'fax_1' => $faker->phoneNumber,
        'fax_2' => $faker->phoneNumber,
        'website' => $faker->url,
        'nom_dg1' => $faker->name,
        'fonct_dg1' => $faker->sentence($nbWords = 6, $variableNbWords = true),
        'gsm_dg1' => $faker->phoneNumber,
        'email_dg1' => $faker->email,
        'nom_dg2' => $faker->name,
        'fonct_dg2' => $faker->sentence($nbWords = 6, $variableNbWords = true),
        'gsm_dg2' => $faker->phoneNumber,
        'email_dg2' => $faker->email,
        'nom_resp' => $faker->name,
        'fonct_resp' => $faker->sentence($nbWords = 6, $variableNbWords = true),
        'gsm_resp' => $faker->phoneNumber,
        'email_resp' => $faker->email,
        'rib' => $faker->creditCardNumber,
        'agence_banc' => $faker->sentence($nbWords = 6, $variableNbWords = true),
        'estim_bgd_DS' => $faker->randomFloat($nbMaxDecimals = NULL, $min = 0, $max = NULL),
        'estim_bdg_IF' => $faker->randomFloat($nbMaxDecimals = NULL, $min = 0, $max = NULL),
        'estim_bdg_PF' => $faker->randomFloat($nbMaxDecimals = NULL, $min = 0, $max = NULL),
        'dt_relation' => $faker->dateTime($max = 'now', $timezone = 'Europe/Paris'),
        'commentaire' => sentence($nbWords = 6, $variableNbWords = true)($nbWords = 100, $variableNbWords = true),
    ];
});
