<?php

namespace App\Imports;

use Maatwebsite\Excel\Concerns\ToModel;
use Maatwebsite\Excel\Concerns\WithValidation;
// use Maatwebsite\Excel\Concerns\WithHeadingRow;
use Maatwebsite\Excel\Concerns\WithMappedCells;
use Maatwebsite\Excel\Concerns\WithCalculatedFormulas; // importer les valeurs à la place des fonctions
use App\Client;

class ClientsSheetImport implements ToModel, WithValidation, WithMappedCells, WithCalculatedFormulas
{
  /**
   * @param array $row
   *
   * @return Client|null
   */
  public function model(array $row)
  {
      return new Client([
          'nrc_entrp' => $row['nrc_entrp'],
          'raisoci' => $row['raisoci'],
          'rais_abrev' => $row['rais_abrev'],
          'formjury' => $row['formjury'],
          'dt_creat' => \PhpOffice\PhpSpreadsheet\Shared\Date::excelToDateTimeObject($row['dt_creat'])->format('Y-m-d'),
          'obj_soci' => $row['obj_soci'],
          'capt_soci' => $row['capt_soci'],
          'sect_activ' => $row['sect_activ'],
          'giac_rattach' => $row['giac_rattach'],
          'ice' => $row['ice'],
          'id_fiscal' => $row['id_fiscal'],
          'ncnss' => $row['ncnss'],
          'npatente' => $row['npatente'],
          'sg_soci' => $row['sg_soci'],
          'chif_aff_1' => $row['chif_aff_1'],
          'chif_aff_2' => $row['chif_aff_2'],
          'chif_aff_3' => $row['chif_aff_3'],
          'chif_aff_4' => $row['chif_aff_4'],
          'local_2' => $row['local_2'],
          'ville' => $row['ville'],
          'effectif' => $row['effectif'],
          'mass_salar' => $row['mass_salar'],
          'tax_form_pers' => $row['tax_form_pers'],
          'der_annee_csf' => $row['der_annee_csf'],
          'nb_permanent' => $row['nb_permanent'],
          'nb_employe' => $row['nb_employe'],
          'nb_occasional' => $row['nb_occasional'],
          'nb_ouvrier' => $row['nb_ouvrier'],
          'nb_cadre' => $row['nb_cadre'],
          'IF1_1' => $row['IF1_1'],
          'DS1_2' => $row['DS1_2'],
          'PF1_3' => $row['PF1_3'],
          'IF2_1' => $row['IF2_1'],
          'DS2_2' => $row['DS2_2'],
          'PF2_3' => $row['PF2_3'],
          'IF3_1' => $row['IF3_1'],
          'DS3_2' => $row['DS3_2'],
          'PF3_3' => $row['PF3_3'],
          'annee_deja1' => $row['annee_deja1'],
          'annee_deja2' => $row['annee_deja2'],
          'annee_deja3' => $row['annee_deja3'],
          'tel_1' => $row['tel_1'],
          'tel_2' => $row['tel_2'],
          'fix_1' => $row['fix_1'],
          'fix_2' => $row['fix_2'],
          'fax_1' => $row['fax_1'],
          'fax_2' => $row['fax_2'],
          'website' => $row['website'],
          'nom_dg1' => $row['nom_dg1'],
          'fonct_dg1' => $row['fonct_dg1'],
          'gsm_dg1' => $row['gsm_dg1'],
          'email_dg1' => $row['email_dg1'],
          'nom_dg2' => $row['nom_dg2'],
          'fonct_dg2' => $row['fonct_dg2'],
          'gsm_dg2' => $row['gsm_dg2'],
          'email_dg2' => $row['email_dg2'],
          'nom_resp' => $row['nom_resp'],
          'fonct_resp' => $row['fonct_resp'],
          'gsm_resp' => $row['gsm_resp'],
          'email_resp' => $row['email_resp'],
          'rib' => $row['rib'],
          'agence_banc' => $row['agence_banc'],
          'estim_bgd_DS' => $row['estim_bgd_DS'],
          'estim_bdg_IF' => $row['estim_bdg_IF'],
          'estim_bdg_PF' => $row['estim_bdg_PF'],
          'dt_relation' => \PhpOffice\PhpSpreadsheet\Shared\Date::excelToDateTimeObject($row['dt_relation'])->format('Y-m-d'),
          'commentaire' => $row['commentaire'],
      ]);
  }

  public function rules(): array {
      return [
        'nrc_entrp'=> 'required|unique:clients|max:20',
        'raisoci'=> 'required|unique:clients|max:100',
        'rais_abrev'=> 'required|unique:clients|max:8',
        'formjury' => 'required|max:50',
        'dt_creat' => 'required|date|before:'.date('Y-m-d'),
        'obj_soci' => 'required|max:50',
        'capt_soci' => 'required|max:15',
        'sect_activ' => 'required|max:50',
        'giac_rattach'=> 'required|max:50',
        'ice'=> 'required|unique:clients|max:50',
        'id_fiscal'=> 'required|unique:clients|max:15',
        'ncnss' => 'required|unique:clients|max:15',
        'npatente' => 'required|unique:clients|max:8',
        'sg_soci' => 'required|max:100',
        'local_2'=> 'required|max:100',
        'ville'=> 'required|max:100',
        'chif_aff_1'=> 'nullable|max:25',
        'chif_aff_2'=> 'nullable|max:25',
        'chif_aff_3'=> 'nullable|max:25',
        'chif_aff_4'=> 'nullable|max:25',
        'effectif'=> 'required|max:5',
        'mass_salar'=> 'max:15',
        'tax_form_pers'=> 'max:15',
        'der_annee_csf' => 'min:4|starts_with:20',
        'nb_permanent'=> 'required|max:3',
        'nb_occasional'=> 'required|max:3',
        'nb_ouvrier'=> 'required|max:3',
        'nb_cadre'=> 'required|max:3',
        'tel_1'=> 'required|max:14',
        'tel_2'=> 'max:14',
        'fix_1'=> 'required|max:14',
        'fix_2'=> 'max:14',
        'fax_1'=> 'max:14',
        'fax_2'=> 'max:14',
        'website'=> 'unique:clients|max:90',
        'nom_dg1'=> 'required|max:50',
        'fonct_dg1'=> 'required|max:50',
        'gsm_dg1'=> 'max:50',
        'email_dg1'=> 'max:50',
        'nom_dg2'=> 'max:50',
        'fonct_dg2'=> 'max:50',
        'gsm_dg2'=> 'max:14',
        'email_dg2'=> 'max:50',
        'nom_resp'=> 'required|max:50',
        'fonct_resp'=> 'required|max:50',
        'gsm_resp'=> 'max:14',
        'email_resp'=> 'max:50',
        'rib'=> 'unique:clients|max:30',
        'agence_banc'=> 'max:30',
        'estim_bgd_DS'=> 'max:15',
        'estim_bdg_IF'=> 'max:15',
        'estim_bdg_PF'=> 'max:15',
        'dt_relation'=> 'required|date|before_or_equal:'.date('Y-m-d'),
        'commentaire'=> 'max:4000'
      ];
  }
  public function mapping(): array
  {
      return [
        'nrc_entrp' => 'B1',
        'raisoci' => 'B2',
        'rais_abrev' => 'B3',
        'formjury' => 'B4',
        'dt_creat' => 'B5',
        'obj_soci' => 'B6',
        'capt_soci' => 'B7',
        'sect_activ' => 'B8',
        'giac_rattach' => 'B9',
        'ice' => 'B10',
        'id_fiscal' => 'B11',
        'ncnss' => 'B12',
        'npatente' => 'B13',
        'sg_soci' => 'B14',
        'chif_aff_1' => 'B15',
        'chif_aff_2' => 'B16',
        'chif_aff_3' => 'B17',
        'chif_aff_4' => 'B18',
        'local_2' => 'B19',
        'ville' => 'B20',
        'effectif' => 'B21',
        'mass_salar' => 'B22',
        'tax_form_pers' => 'B23',
        'der_annee_csf' => 'B24',
        'nb_permanent' => 'B25',
        'nb_employe' => 'B26',
        'nb_occasional' => 'B27',
        'nb_ouvrier' => 'B28',
        'nb_cadre' => 'B39',
        'IF1_1' => 'B30',
        'DS1_2' => 'B31',
        'PF1_3' => 'B32',
        'IF2_1' => 'B33',
        'DS2_2' => 'B34',
        'PF2_3' => 'B35',
        'IF3_1' => 'B36',
        'DS3_2' => 'B37',
        'PF3_3' => 'B38',
        'annee_deja1' => 'B39',
        'annee_deja2' => 'B40',
        'annee_deja3' => 'B41',
        'tel_1' => 'B42',
        'tel_2' => 'B43',
        'fix_1' => 'B44',
        'fix_2' => 'B45',
        'fax_1' => 'B46',
        'fax_2' => 'B47',
        'website' => 'B48',
        'nom_dg1' => 'B49',
        'fonct_dg1' => 'B50',
        'gsm_dg1' => 'B51',
        'email_dg1' => 'B52',
        'nom_dg2' => 'B53',
        'fonct_dg2' => 'B54',
        'gsm_dg2' => 'B55',
        'email_dg2' => 'B56',
        'nom_resp' => 'B57',
        'fonct_resp' => 'B58',
        'gsm_resp' => 'B59',
        'email_resp' => 'B60',
        'rib' => 'B61',
        'agence_banc' => 'B62',
        'estim_bgd_DS' => 'B63',
        'estim_bdg_IF' => 'B64',
        'estim_bdg_PF' => 'B65',
        'dt_relation' => 'B66',
        'commentaire' => 'B67'
      ];
  } // mapping

}
